application: hangoutsangular
version: 1
runtime: php55
module: default
api_version: 1

handlers:
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /xml
  static_dir: xml
  
- url: /.*
  script: index.html
  